const TAGS = {
  GENERAL: [
    { id: 62, name: 'vegan' },
    { id: 63, name: 'vegetarian' },
    { id: 64, name: 'low carb' },
    { id: 65, name: 'diet' },
    { id: 66, name: 'satiating' },
    { id: 67, name: 'high protein' },
    { id: 68, name: 'gluten free' },
    { id: 69, name: 'few ingredients' },
    { id: 70, name: 'quick' },
    { id: 71, name: 'easy' },
  ],
  FLAVOR: [
    { id: 72, name: 'sweet' },
    { id: 73, name: 'spicy' },
    { id: 74, name: 'hearty' },
    { id: 75, name: 'fresh' },
    { id: 76, name: 'bold' },
  ],
  COURSE: [
    { id: 77, name: 'dinner' },
    { id: 78, name: 'breakfast' },
    { id: 79, name: 'side' },
    { id: 80, name: 'snack' },
    { id: 81, name: 'dessert' },
  ],
  CUISINE: [
    { id: 82, name: 'italian' },
    { id: 83, name: 'german' },
    { id: 84, name: 'american' },
    { id: 85, name: 'vietnamese' },
    { id: 86, name: 'chinese' },
    { id: 87, name: 'japanese' },
    { id: 88, name: 'french' },
    { id: 89, name: 'british' },
    { id: 90, name: 'mexican' },
    { id: 91, name: 'indian' },
    { id: 92, name: 'spanish' },
    { id: 93, name: 'middle eastern' },
    { id: 94, name: 'thai' },
  ],
} as const;

export default TAGS;
